keys:
  - &media age1d4yfd50xx5l8h9x2dsecwh4afjgrs2hqrd5yatqjm4fq63jej4rsa2d90u
  - &razer age1quy67nc45mn5d2af0td0trcamn4576ete2jzarpmvmvf4cjdm3gqhkf4kw
creation_rules:
  - path_regex: hosts/media-server/.*$
    key_groups:
      - age:
          - *media
          - *razer
